### ISSUE TITLE
application ideas

### ISSUE THREAD

**Issue by yipperr** [jbush001/NyuziProcessor#18]
hello sorry for asking this question but i was wondering if people can list what THIS gpugpu processor is good for once synthesized i don't want a general what gpgpu is good for but what this project will help speedup or facilitate

**Comment by jbush001** [comment]
I'm a bit fuzzy on what you mean specifically by "good for," but I'll try to answer your question. This is designed for problems that are highly parallel, so it can execute any GPGPU-like algorithm (that is, anything that can be broken down into many smaller tasks).

Where it may have an advantage over a traditional GPU architecture is on problems that have some irregularity. For example, something like Barnes Hut might be easier to implement on an architecture like this one than in OpenCL because this can more easily access complex, irregular data structures and perform recursion. One area that I think would be interesting to explore would be real time image processing. 

If your question is whether there are specific use cases that are currently targeted for this project, the answer is no.
